name: CMake (macOS)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install libraries
      run: brew install web-eid/gtest/gtest

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${BUILD_TYPE}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C ${BUILD_TYPE}
