name: CMake (Windows)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: Prepare vcpkg and libraries
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgArguments: gtest:x64-windows
        vcpkgTriplet: x64-windows
        vcpkgDirectory: ${{runner.workspace}}/vcpkg/
        vcpkgGitCommitId: 9b064ff07b987c8f213fdbf4358122fd4fe38ef1

    - name: Configure CMake
      run: cmake -A x64 "-DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=${env:BUILD_TYPE}" -B build -S .

    - name: Build
      run: cmake --build build --config ${env:BUILD_TYPE}

    - name: Test
      run: ctest -V -C ${env:BUILD_TYPE} --test-dir build
